# Generated by Django 5.0.6 on 2024-06-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='recurrence_rule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='icalendar',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
