# Generated by Django 5.0.6 on 2024-06-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_schedule_recurrence_rule_schedule_icalendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='icalendar',
            new_name='icalendar_data',
        ),
    ]
