# Generated by Django 5.0.6 on 2024-06-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_ticket_type_ticket_type_remove_ticket_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="images",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="type",
            field=models.CharField(
                choices=[
                    ("family", "Семейный"),
                    ("group", "Групповой"),
                    ("adult", "Взрослый"),
                    ("child", "Детский"),
                    ("discount", "Льготный"),
                ],
                max_length=50,
            ),
        ),
    ]
