# Generated by Django 5.0.6 on 2024-06-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_place_images_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.JSONField(),
        ),
    ]
