# Generated by Django 5.0.6 on 2024-06-14 02:18

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_place_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="images",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=apps.core.models.get_image_path)),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.place",
                    ),
                ),
            ],
        ),
    ]
