# Generated by Django 5.0.6 on 2024-06-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_short_name_place_abbreviation_place_short_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='src',
        ),
    ]
