# Generated by Django 5.0.6 on 2024-06-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0007_remove_booking_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('html_message', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PROCESSING', max_length=10)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailer.mail')),
                ('recipients', models.ManyToManyField(related_name='mailings', to='booking.buyer')),
            ],
        ),
    ]
