# Generated by Django 5.0.6 on 2024-06-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ticket_file",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
