# Generated by Django 5.0.6 on 2024-06-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_order_ticket_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="return_url",
        ),
    ]
