# Generated by Django 5.0.6 on 2024-06-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_remove_order_return_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
