# Generated by Django 5.0.6 on 2024-06-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_cartticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tickets',
        ),
        migrations.AlterField(
            model_name='cartticket',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.cart'),
        ),
    ]
