# Generated by Django 5.0.6 on 2024-06-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_cart_tickets_alter_cartticket_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
