# Generated by Django 5.0.6 on 2024-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_cart_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
