# Generated by Django 5.0.6 on 2024-06-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_booking_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="file",
        ),
    ]
