# Generated by Django 5.0.6 on 2024-06-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_quantity'),
        ('payments', '0005_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='payments.order'),
            preserve_default=False,
        ),
    ]
