name: Docker Compose CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and start containers
        run: |
          cd backend
          docker-compose up -d --build

      - name: Wait for services to be up
        run: |
          cd backend
          services=$(docker-compose config --services)
          for service in $services; do
            while ! docker-compose ps $service | grep -q "Up"; do
              echo "Waiting for $service to be up..."
              sleep 5
            done
          done

      - name: Check container status
        run: |
          cd backend
          services=$(docker-compose config --services)
          for service in $services; do
            status=$(docker inspect -f '{{.State.Status}}' $(docker-compose ps -q $service))
            if [ "$status" != "running" ]; then
              echo "$service is not running."
              exit 1
            fi
          done
