name: Docker Compose CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and start containers
        run: |
          cd backend
          cp .env.example .env
          docker-compose up -d --build

      - name: Wait for services to be up
        run: |
          echo "Waiting for services to be up..."
          sleep 30

      - name: Check Docker Compose Services
        run: docker-compose ps

      - name: Check for unhealthy services and restarts
        run: |
          services=$(docker-compose ps --services)
          for service in $services; do
            health_status=$(docker inspect --format='{{json .State.Health.Status}}' $(docker-compose ps -q $service))
            restart_count=$(docker inspect --format='{{.RestartCount}}' $(docker-compose ps -q $service))
          
            echo "Service: $service, Health: $health_status, Restarts: $restart_count"
          
            if [[ "$health_status" != "\"healthy\"" ]]; then
              echo "Error: Service $service is not healthy"
              docker-compose logs $service
              exit 1
            fi
          
            if [[ "$restart_count" -gt 0 ]]; then
              echo "Error: Service $service has restarted $restart_count times"
              docker-compose logs $service
              exit 1
            fi
          done

      - name: Stop and remove Docker Compose services
        run: docker-compose down
